### ISSUE TITLE
VIRAT/ActEV data lost

### ISSUE THREAD

**Issue by Lesballes** [Jacobieee/ST-MR#1]
hello jacobieee! I am very interseted in your work. But in first step "preprocessing step", multiverse author could not supply the data. would you mind to send the "three .npz" files via baidu cloud or aliyun cloud or 919806472@qq.com? Thank you a lot!
here is the "preprocessing step":
Follow the [preprocessing step](https://github.com/JunweiLiang/Multiverse/blob/master/TRAINING.md#step-1-preprocess) in Multiverse repo and generate three .npz files with all trajectory inputs and features.

**Comment by Jacobieee** [comment]
Hello, sorry for the late reply.
I have seen the owner of the Multiverse repo has recovered the link for downloading the dataset, please check this [issue](https://github.com/JunweiLiang/Multiverse/issues/39#issuecomment-1425997830).
